### ISSUE TITLE
跑不起来，请问这是什么问题

### ISSUE THREAD

**Issue by forsunforfree** [arterli/CmsWing#32]
![image](https://user-images.githubusercontent.com/34706007/40406613-ea8570b6-5e93-11e8-820e-474e3b8045ea.png)

**Comment by arterli** [comment]
数据库的问题，拒绝链接

**Comment by arterli** [comment]
https://www.cmswing.com/p/404.html

**Comment by forsunforfree** [comment]
感谢大神，点赞
