### ISSUE TITLE
非常好的电子商务模板

### ISSUE THREAD

**Issue by magicknight** [arterli/CmsWing#4]
我想做个社区内居民互相买卖二手货的小站点，javascript算刚入门，请问一下，如果要给您的模板加上用户可以发布商品信息的功能，难度有多大？谢谢！

**Comment by arterli** [comment]
现在还是开发版，正式版还没发布，如果用正式版二次开发。基本上80%的功能符合你的需求。你只需要，修改模版，和微调就可以了。
