### ISSUE TITLE
最新clone下来的版本，后台管理出现格式错误，内容管理看不到内容，报500错误。

### ISSUE THREAD

**Issue by CHparis** [arterli/CmsWing#6]
![image](https://cloud.githubusercontent.com/assets/5772119/16906337/ab916be4-4ce8-11e6-9b0b-be786b4e0a15.png)
![image](https://cloud.githubusercontent.com/assets/5772119/16906362/f3a82882-4ce8-11e6-82f2-992700c87a39.png)

**Comment by CHparis** [comment]
微信功能clone到本地运行出来，也不能正常使用了。

**Comment by arterli** [comment]
我本地，和线上都没问题啊。

**Comment by CHparis** [comment]
原来是缓存问题，已解决，删除本地的runtime文件夹就可以了。
